// <auto-generated />
using System;
using ClubMedAPI.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubMedAPI.Migrations
{
    [DbContext(typeof(ClubMedContext))]
    partial class ClubMedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Activite", b =>
                {
                    b.Property<int>("IdActivite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idactivite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdActivite"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<int?>("IdPartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("idpartenaire");

                    b.Property<decimal>("PrixMin")
                        .HasColumnType("numeric")
                        .HasColumnName("prixmin");

                    b.Property<string>("Titre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("titre");

                    b.HasKey("IdActivite");

                    b.HasIndex("IdPartenaire");

                    b.ToTable("activite");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.ActiviteAdulte", b =>
                {
                    b.Property<int>("IdActivite")
                        .HasColumnType("integer")
                        .HasColumnName("idactivite");

                    b.Property<int>("AgeMinimum")
                        .HasColumnType("integer")
                        .HasColumnName("ageminimum");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<decimal>("Duree")
                        .HasColumnType("numeric")
                        .HasColumnName("duree");

                    b.Property<string>("Frequence")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("frequence");

                    b.Property<int>("NumTypeActivite")
                        .HasColumnType("integer")
                        .HasColumnName("numtypeactivite");

                    b.Property<decimal>("PrixMin")
                        .HasColumnType("numeric")
                        .HasColumnName("prixmin");

                    b.Property<string>("Titre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("titre");

                    b.HasKey("IdActivite");

                    b.HasIndex("NumTypeActivite");

                    b.ToTable("activiteadulte");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.ActiviteEnfant", b =>
                {
                    b.Property<int>("IdActivite")
                        .HasColumnType("integer")
                        .HasColumnName("idactivite");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("detail");

                    b.Property<int>("NumTranche")
                        .HasColumnType("integer")
                        .HasColumnName("numtranche");

                    b.Property<decimal>("PrixMin")
                        .HasColumnType("numeric")
                        .HasColumnName("prixmin");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("titre");

                    b.HasKey("IdActivite");

                    b.HasIndex("NumTranche");

                    b.ToTable("activiteenfant");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("NumAdresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numadresse");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumAdresse"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("codepostal");

                    b.Property<string>("NomRue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nomrue");

                    b.Property<int>("NumRue")
                        .HasColumnType("integer")
                        .HasColumnName("numrue");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("pays");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ville");

                    b.HasKey("NumAdresse");

                    b.ToTable("adresse");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.AutreVoyageur", b =>
                {
                    b.Property<int>("NumVoyageur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numvoyageur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumVoyageur"));

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("datenaissance");

                    b.Property<string>("Genre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("genre");

                    b.Property<string>("Nom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nom");

                    b.Property<int>("NumReservation")
                        .HasColumnType("integer")
                        .HasColumnName("numreservation");

                    b.Property<string>("Prenom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("prenom");

                    b.HasKey("NumVoyageur");

                    b.HasIndex("NumReservation");

                    b.ToTable("autrevoyageur");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Avis", b =>
                {
                    b.Property<int>("NumAvis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numavis");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumAvis"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("commentaire");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("idclub");

                    b.Property<int>("Note")
                        .HasColumnType("integer")
                        .HasColumnName("note");

                    b.Property<int>("NumClient")
                        .HasColumnType("integer")
                        .HasColumnName("numclient");

                    b.Property<int>("NumReservation")
                        .HasColumnType("integer")
                        .HasColumnName("numreservation");

                    b.Property<string>("Reponse")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reponse");

                    b.Property<string>("Titre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("titre");

                    b.HasKey("NumAvis");

                    b.HasIndex("IdClub");

                    b.HasIndex("NumClient");

                    b.HasIndex("NumReservation");

                    b.ToTable("avis");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Calendrier", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("Date");

                    b.ToTable("calendrier");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.CarteBancaire", b =>
                {
                    b.Property<int>("IdCb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcb");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCb"));

                    b.Property<string>("CvvCrypter")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cvv_crypter");

                    b.Property<string>("DateExpirationCarteBancaire")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("dateexpiration_carte_bancaire");

                    b.Property<bool>("EstActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("est_active");

                    b.Property<string>("NumCarteBancaireCrypter")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("numcartebancaire_crypter");

                    b.Property<int?>("NumClient")
                        .HasColumnType("integer")
                        .HasColumnName("numclient");

                    b.HasKey("IdCb");

                    b.HasIndex("NumClient");

                    b.ToTable("carte_bancaire");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Categorie", b =>
                {
                    b.Property<int>("NumCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numcategory");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumCategory"));

                    b.Property<string>("NomCategory")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nomcategory");

                    b.HasKey("NumCategory");

                    b.ToTable("categorie");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Chambre", b =>
                {
                    b.Property<int>("NumChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numchambre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumChambre"));

                    b.Property<int>("IdTypeChambre")
                        .HasColumnType("integer")
                        .HasColumnName("idtypechambre");

                    b.HasKey("NumChambre");

                    b.HasIndex("IdTypeChambre");

                    b.ToTable("chambre");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Client", b =>
                {
                    b.Property<int>("NumClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numclient");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumClient"));

                    b.Property<bool>("A2fActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("a2f_active");

                    b.Property<string>("A2fMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("a2f_method");

                    b.Property<string>("CvvCrypter")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cvv_crypter");

                    b.Property<string>("DateExpirationCarteBancaire")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("dateexpiration_carte_bancaire");

                    b.Property<DateOnly?>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("datenaissance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("email");

                    b.Property<string>("Genre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("genre");

                    b.Property<string>("MotDePasseCrypter")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("motdepasse_crypter");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nom");

                    b.Property<int?>("NumAdresse")
                        .HasColumnType("integer")
                        .HasColumnName("numadresse");

                    b.Property<string>("NumCarteBancaireCrypter")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("numcartebancaire_crypter");

                    b.Property<string>("PmLastFour")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("pm_last_four");

                    b.Property<string>("PmType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pm_type");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("client")
                        .HasColumnName("role");

                    b.Property<string>("StripeId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_id");

                    b.Property<string>("Telephone")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("telephone");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("totp_secret");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("trial_ends_at");

                    b.HasKey("NumClient");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NumAdresse");

                    b.ToTable("client");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Club", b =>
                {
                    b.Property<int>("IdClub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idclub");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClub"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("LienPdf")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("lienpdf");

                    b.Property<decimal?>("NoteMoyenne")
                        .HasColumnType("numeric")
                        .HasColumnName("notemoyenne");

                    b.Property<int?>("NumPays")
                        .HasColumnType("integer")
                        .HasColumnName("numpays");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("numphoto");

                    b.Property<string>("StatutMiseEnLigne")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("EN_CREATION")
                        .HasColumnName("statut_mise_en_ligne");

                    b.Property<string>("Titre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("titre");

                    b.HasKey("IdClub");

                    b.HasIndex("NumPays");

                    b.HasIndex("NumPhoto");

                    b.ToTable("club");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.ClubStation", b =>
                {
                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("idclub");

                    b.Property<int>("NumStation")
                        .HasColumnType("integer")
                        .HasColumnName("numstation");

                    b.Property<string>("AltitudeClub")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("altitudeclub");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("LienPdf")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("lienpdf");

                    b.Property<decimal?>("NoteMoyenne")
                        .HasColumnType("numeric")
                        .HasColumnName("notemoyenne");

                    b.Property<int?>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("numphoto");

                    b.Property<string>("Titre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("titre");

                    b.HasKey("IdClub", "NumStation");

                    b.HasIndex("NumPhoto");

                    b.HasIndex("NumStation");

                    b.ToTable("clubstation", (string)null);
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.DateCalendrier", b =>
                {
                    b.Property<DateOnly>("Jour")
                        .HasColumnType("date")
                        .HasColumnName("jour");

                    b.HasKey("Jour");

                    b.ToTable("date_calendrier");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Disponibilite", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("NumChambre")
                        .HasColumnType("integer")
                        .HasColumnName("numchambre");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("idclub");

                    b.Property<bool?>("EstDisponibilite")
                        .HasColumnType("boolean")
                        .HasColumnName("estdisponibilite");

                    b.HasKey("Date", "NumChambre", "IdClub");

                    b.HasIndex("IdClub");

                    b.HasIndex("NumChambre");

                    b.ToTable("disponibilite");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Equipement", b =>
                {
                    b.Property<int>("NumEquipement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numequipement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumEquipement"));

                    b.Property<string>("Nom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nom");

                    b.Property<int>("NumIcon")
                        .HasColumnType("integer")
                        .HasColumnName("numicon");

                    b.HasKey("NumEquipement");

                    b.HasIndex("NumIcon");

                    b.ToTable("equipement");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.EquipementSalleDeBain", b =>
                {
                    b.Property<int>("NumEquipementSalleBain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numequipementsallebain");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumEquipementSalleBain"));

                    b.Property<string>("Nom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nom");

                    b.HasKey("NumEquipementSalleBain");

                    b.ToTable("equipementsalledebain");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Icon", b =>
                {
                    b.Property<int>("NumIcon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numicon");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumIcon"));

                    b.Property<string>("LienIcon")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("lienicon");

                    b.Property<int>("NumEquipementSalleBain")
                        .HasColumnType("integer")
                        .HasColumnName("numequipementsallebain");

                    b.Property<int>("NumPointFort")
                        .HasColumnType("integer")
                        .HasColumnName("numpointfort");

                    b.Property<int>("NumService")
                        .HasColumnType("integer")
                        .HasColumnName("numservice");

                    b.HasKey("NumIcon");

                    b.HasIndex("NumEquipementSalleBain");

                    b.HasIndex("NumPointFort");

                    b.HasIndex("NumService");

                    b.ToTable("icon");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.LieuRestauration", b =>
                {
                    b.Property<int>("NumRestauration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numrestauration");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumRestauration"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<bool?>("EstBar")
                        .HasColumnType("boolean")
                        .HasColumnName("estbar");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nom");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("numphoto");

                    b.Property<string>("Presentation")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("presentation");

                    b.HasKey("NumRestauration");

                    b.HasIndex("NumPhoto");

                    b.ToTable("lieurestauration");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Localisation", b =>
                {
                    b.Property<int>("NumLocalisation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numlocalisation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumLocalisation"));

                    b.Property<string>("NomLocalisation")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nomlocalisation");

                    b.HasKey("NumLocalisation");

                    b.ToTable("localisation");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Partenaire", b =>
                {
                    b.Property<int>("IdPartenaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idpartenaire");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPartenaire"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telephone");

                    b.HasKey("IdPartenaire");

                    b.ToTable("partenaires");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Periode", b =>
                {
                    b.Property<string>("NumPeriode")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("numperiode");

                    b.Property<DateOnly?>("DateDeb")
                        .HasColumnType("date")
                        .HasColumnName("datedeb");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("datefin");

                    b.HasKey("NumPeriode");

                    b.ToTable("periode");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Photo", b =>
                {
                    b.Property<int>("NumPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numphoto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumPhoto"));

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.HasKey("NumPhoto");

                    b.ToTable("photo");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.PhotoClub", b =>
                {
                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("idclub");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("numphoto");

                    b.Property<int?>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("ordre");

                    b.HasKey("IdClub", "NumPhoto");

                    b.HasIndex("NumPhoto");

                    b.ToTable("photo_club", (string)null);
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.PointFort", b =>
                {
                    b.Property<int>("NumPointFort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numpointfort");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumPointFort"));

                    b.Property<string>("Nom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nom");

                    b.HasKey("NumPointFort");

                    b.ToTable("pointfort");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.PrixPeriode", b =>
                {
                    b.Property<string>("NumPeriode")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("numperiode");

                    b.Property<int>("IdTypeChambre")
                        .HasColumnType("integer")
                        .HasColumnName("idtypechambre");

                    b.Property<decimal?>("PrixPeriodeValue")
                        .HasColumnType("numeric")
                        .HasColumnName("prixperiode");

                    b.HasKey("NumPeriode", "IdTypeChambre");

                    b.HasIndex("IdTypeChambre");

                    b.ToTable("prix_periode");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Regroupement", b =>
                {
                    b.Property<int>("NumRegroupement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numregroupement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumRegroupement"));

                    b.Property<string>("LibelleRegroupement")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("libelleregroupement");

                    b.HasKey("NumRegroupement");

                    b.ToTable("regroupement");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Reservation", b =>
                {
                    b.Property<int>("NumReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numreservation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumReservation"));

                    b.Property<DateOnly?>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("datedebut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("datefin");

                    b.Property<bool>("DisponibiliteConfirmee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("disponibilite_confirmee");

                    b.Property<string>("EtatCalcule")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("etat_calcule");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("idclub");

                    b.Property<string>("IdTransport")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("idtransport");

                    b.Property<string>("LieuDepart")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("lieudepart");

                    b.Property<bool>("Mail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mail");

                    b.Property<bool?>("MailConfirmationEnvoye")
                        .HasColumnType("boolean")
                        .HasColumnName("mail_confirmation_envoye");

                    b.Property<int?>("NbPersonnes")
                        .HasColumnType("integer")
                        .HasColumnName("nbpersonnes");

                    b.Property<int>("NumClient")
                        .HasColumnType("integer")
                        .HasColumnName("numclient");

                    b.Property<decimal?>("Prix")
                        .HasColumnType("numeric")
                        .HasColumnName("prix");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("EN_ATTENTE")
                        .HasColumnName("statut");

                    b.Property<string>("TokenPartenaire")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_partenaire");

                    b.Property<bool>("VeutAnnuler")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("veut_annuler");

                    b.HasKey("NumReservation");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdTransport");

                    b.HasIndex("NumClient");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.ReservationActivite", b =>
                {
                    b.Property<int>("NumReservation")
                        .HasColumnType("integer")
                        .HasColumnName("numreservation");

                    b.Property<int>("IdActivite")
                        .HasColumnType("integer")
                        .HasColumnName("idactivite");

                    b.Property<DateOnly?>("DateEnvoi")
                        .HasColumnType("date")
                        .HasColumnName("date_envoi");

                    b.Property<bool>("DisponibiliteConfirmee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("disponibilite_confirmee");

                    b.Property<int>("NbPersonnes")
                        .HasColumnType("integer")
                        .HasColumnName("nbpersonnes");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.HasKey("NumReservation", "IdActivite");

                    b.HasIndex("IdActivite");

                    b.ToTable("se_lie_a");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Service", b =>
                {
                    b.Property<int>("NumService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numservice");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumService"));

                    b.Property<string>("Nom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nom");

                    b.HasKey("NumService");

                    b.ToTable("service");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.SousLocalisation", b =>
                {
                    b.Property<int>("NumPays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numpays");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumPays"));

                    b.Property<string>("NomPays")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nompays");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("numphoto");

                    b.HasKey("NumPays");

                    b.HasIndex("NumPhoto");

                    b.ToTable("souslocalisation");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Station", b =>
                {
                    b.Property<int>("NumStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numstation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumStation"));

                    b.Property<decimal>("AltitudeStation")
                        .HasColumnType("numeric")
                        .HasColumnName("altitudestation");

                    b.Property<string>("InfoSki")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("infoski");

                    b.Property<decimal>("LongueurPistes")
                        .HasColumnType("numeric")
                        .HasColumnName("longueurpistes");

                    b.Property<int>("NbPistes")
                        .HasColumnType("integer")
                        .HasColumnName("nbpistes");

                    b.Property<string>("NomStation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nomstation");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("numphoto");

                    b.HasKey("NumStation");

                    b.HasIndex("NumPhoto");

                    b.ToTable("station");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.TrancheAge", b =>
                {
                    b.Property<int>("NumTranche")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numtranche");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumTranche"));

                    b.Property<int?>("AgeMax")
                        .HasColumnType("integer")
                        .HasColumnName("agemax");

                    b.Property<int?>("AgeMin")
                        .HasColumnType("integer")
                        .HasColumnName("agemin");

                    b.HasKey("NumTranche");

                    b.ToTable("trancheage");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Transaction", b =>
                {
                    b.Property<int>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtransaction");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransaction"));

                    b.Property<DateTime?>("DateTransaction")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_transaction");

                    b.Property<int?>("IdCb")
                        .HasColumnType("integer")
                        .HasColumnName("idcb");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("numeric")
                        .HasColumnName("montant");

                    b.Property<string>("MoyenPaiement")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("moyen_paiement");

                    b.Property<int>("NumReservation")
                        .HasColumnType("integer")
                        .HasColumnName("numreservation");

                    b.Property<string>("StatutPaiement")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut_paiement");

                    b.HasKey("IdTransaction");

                    b.HasIndex("IdCb");

                    b.HasIndex("NumReservation");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Transport", b =>
                {
                    b.Property<string>("IdTransport")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("idtransport");

                    b.Property<string>("LieuDepart")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("lieudepart");

                    b.Property<decimal?>("Prix")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prix");

                    b.HasKey("IdTransport");

                    b.ToTable("transport");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.TypeActivite", b =>
                {
                    b.Property<int>("NumTypeActivite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numtypeactivite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumTypeActivite"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<int>("NbActiviteCarte")
                        .HasColumnType("integer")
                        .HasColumnName("nbactivitecarte");

                    b.Property<int>("NbActiviteIncluse")
                        .HasColumnType("integer")
                        .HasColumnName("nbactiviteincluse");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("numphoto");

                    b.Property<string>("Titre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("titre");

                    b.HasKey("NumTypeActivite");

                    b.HasIndex("NumPhoto");

                    b.ToTable("typeactivite");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.TypeChambre", b =>
                {
                    b.Property<int>("IdTypeChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtypechambre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeChambre"));

                    b.Property<int?>("CapaciteMax")
                        .HasColumnType("integer")
                        .HasColumnName("capacitemax");

                    b.Property<int?>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("idclub");

                    b.Property<bool>("Indisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("indisponible");

                    b.Property<decimal?>("MetresCarres")
                        .HasColumnType("numeric")
                        .HasColumnName("metrescarres");

                    b.Property<string>("NomType")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nomtype");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("numphoto");

                    b.Property<string>("TextePresentation")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("textepresentation");

                    b.HasKey("IdTypeChambre");

                    b.HasIndex("IdClub");

                    b.HasIndex("NumPhoto");

                    b.ToTable("typechambre");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.TypeClub", b =>
                {
                    b.Property<int>("NumType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("numtype");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumType"));

                    b.Property<string>("NomType")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("nomtype");

                    b.HasKey("NumType");

                    b.ToTable("typeclub");
                });

            modelBuilder.Entity("assure_la_liaison_avec", b =>
                {
                    b.Property<int>("idtypechambre")
                        .HasColumnType("integer");

                    b.Property<int>("numequipementsallebain")
                        .HasColumnType("integer");

                    b.HasKey("idtypechambre", "numequipementsallebain");

                    b.HasIndex("numequipementsallebain");

                    b.ToTable("assure_la_liaison_avec");
                });

            modelBuilder.Entity("collabore", b =>
                {
                    b.Property<int>("idclub")
                        .HasColumnType("integer");

                    b.Property<int>("numcategory")
                        .HasColumnType("integer");

                    b.HasKey("idclub", "numcategory");

                    b.HasIndex("numcategory");

                    b.ToTable("collabore");
                });

            modelBuilder.Entity("converge_vers", b =>
                {
                    b.Property<int>("idclub")
                        .HasColumnType("integer");

                    b.Property<int>("numregroupement")
                        .HasColumnType("integer");

                    b.HasKey("idclub", "numregroupement");

                    b.HasIndex("numregroupement");

                    b.ToTable("converge_vers");
                });

            modelBuilder.Entity("fusionne", b =>
                {
                    b.Property<int>("idclub")
                        .HasColumnType("integer");

                    b.Property<int>("numrestauration")
                        .HasColumnType("integer");

                    b.HasKey("idclub", "numrestauration");

                    b.HasIndex("numrestauration");

                    b.ToTable("fusionne");
                });

            modelBuilder.Entity("fusionne_avec", b =>
                {
                    b.Property<int>("numcategory")
                        .HasColumnType("integer");

                    b.Property<int>("numlocalisation")
                        .HasColumnType("integer");

                    b.HasKey("numcategory", "numlocalisation");

                    b.HasIndex("numlocalisation");

                    b.ToTable("fusionne_avec");
                });

            modelBuilder.Entity("incruste_avec", b =>
                {
                    b.Property<int>("idactivite")
                        .HasColumnType("integer");

                    b.Property<int>("idclub")
                        .HasColumnType("integer");

                    b.HasKey("idactivite", "idclub");

                    b.HasIndex("idclub");

                    b.ToTable("incruste_avec");
                });

            modelBuilder.Entity("photoavis", b =>
                {
                    b.Property<int>("numavis")
                        .HasColumnType("integer");

                    b.Property<int>("numphoto")
                        .HasColumnType("integer");

                    b.HasKey("numavis", "numphoto");

                    b.HasIndex("numphoto");

                    b.ToTable("photoavis");
                });

            modelBuilder.Entity("s_articule_autour_de", b =>
                {
                    b.Property<int>("numlocalisation")
                        .HasColumnType("integer");

                    b.Property<int>("numpays")
                        .HasColumnType("integer");

                    b.HasKey("numlocalisation", "numpays");

                    b.HasIndex("numpays");

                    b.ToTable("s_articule_autour_de");
                });

            modelBuilder.Entity("s_harmonise_avec", b =>
                {
                    b.Property<int>("numcategory")
                        .HasColumnType("integer");

                    b.Property<int>("numtype")
                        .HasColumnType("integer");

                    b.HasKey("numcategory", "numtype");

                    b.HasIndex("numtype");

                    b.ToTable("s_harmonise_avec");
                });

            modelBuilder.Entity("s_imbrique_dans", b =>
                {
                    b.Property<int>("idtypechambre")
                        .HasColumnType("integer");

                    b.Property<int>("numservice")
                        .HasColumnType("integer");

                    b.HasKey("idtypechambre", "numservice");

                    b.HasIndex("numservice");

                    b.ToTable("s_imbrique_dans");
                });

            modelBuilder.Entity("s_influence_mutuellement", b =>
                {
                    b.Property<int>("idtypechambre")
                        .HasColumnType("integer");

                    b.Property<int>("numchambre")
                        .HasColumnType("integer");

                    b.HasKey("idtypechambre", "numchambre");

                    b.HasIndex("numchambre");

                    b.ToTable("s_influence_mutuellement");
                });

            modelBuilder.Entity("s_unit_a", b =>
                {
                    b.Property<int>("idclub")
                        .HasColumnType("integer");

                    b.Property<int>("numchambre")
                        .HasColumnType("integer");

                    b.HasKey("idclub", "numchambre");

                    b.HasIndex("numchambre");

                    b.ToTable("s_unit_a");
                });

            modelBuilder.Entity("se_met_en_harmonie_avec", b =>
                {
                    b.Property<int>("idtypechambre")
                        .HasColumnType("integer");

                    b.Property<int>("numequipement")
                        .HasColumnType("integer");

                    b.HasKey("idtypechambre", "numequipement");

                    b.HasIndex("numequipement");

                    b.ToTable("se_met_en_harmonie_avec");
                });

            modelBuilder.Entity("synchronise", b =>
                {
                    b.Property<int>("idtypechambre")
                        .HasColumnType("integer");

                    b.Property<int>("numpointfort")
                        .HasColumnType("integer");

                    b.HasKey("idtypechambre", "numpointfort");

                    b.HasIndex("numpointfort");

                    b.ToTable("synchronise");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Activite", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Partenaire", "Partenaire")
                        .WithMany("Activites")
                        .HasForeignKey("IdPartenaire");

                    b.Navigation("Partenaire");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.ActiviteAdulte", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Activite", "Activite")
                        .WithOne("Adulte")
                        .HasForeignKey("ClubMedAPI.Models.EntityFramework.ActiviteAdulte", "IdActivite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.TypeActivite", "TypeActivite")
                        .WithMany("ActivitesAdultes")
                        .HasForeignKey("NumTypeActivite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activite");

                    b.Navigation("TypeActivite");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.ActiviteEnfant", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Activite", "Activite")
                        .WithOne("Enfant")
                        .HasForeignKey("ClubMedAPI.Models.EntityFramework.ActiviteEnfant", "IdActivite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.TrancheAge", "TrancheAge")
                        .WithMany("ActivitesEnfants")
                        .HasForeignKey("NumTranche")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activite");

                    b.Navigation("TrancheAge");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.AutreVoyageur", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Reservation", "Reservation")
                        .WithMany("AutresVoyageurs")
                        .HasForeignKey("NumReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Avis", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", "Club")
                        .WithMany("Avis")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Client", "Client")
                        .WithMany("Avis")
                        .HasForeignKey("NumClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Reservation", "Reservation")
                        .WithMany("Avis")
                        .HasForeignKey("NumReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Club");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.CarteBancaire", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Client", "Client")
                        .WithMany("CartesBancaires")
                        .HasForeignKey("NumClient");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Chambre", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.TypeChambre", "TypeChambre")
                        .WithMany("Chambres")
                        .HasForeignKey("IdTypeChambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeChambre");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Client", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Adresse", "Adresse")
                        .WithMany("Clients")
                        .HasForeignKey("NumAdresse");

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Club", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.SousLocalisation", "Pays")
                        .WithMany("Clubs")
                        .HasForeignKey("NumPays");

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Photo", "Photo")
                        .WithMany("ClubsAvecCettePhoto")
                        .HasForeignKey("NumPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pays");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.ClubStation", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", "Club")
                        .WithMany()
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("NumPhoto");

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Station", "Station")
                        .WithMany()
                        .HasForeignKey("NumStation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Photo");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Disponibilite", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", "Club")
                        .WithMany("Disponibilites")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Chambre", "Chambre")
                        .WithMany("Disponibilites")
                        .HasForeignKey("NumChambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chambre");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Equipement", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Icon", "Icon")
                        .WithMany("Equipements")
                        .HasForeignKey("NumIcon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Icon", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.EquipementSalleDeBain", "EquipementSalleDeBain")
                        .WithMany("Icons")
                        .HasForeignKey("NumEquipementSalleBain")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.PointFort", "PointFort")
                        .WithMany("Icons")
                        .HasForeignKey("NumPointFort")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Service", "Service")
                        .WithMany("Icons")
                        .HasForeignKey("NumService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipementSalleDeBain");

                    b.Navigation("PointFort");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.LieuRestauration", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Photo", "Photo")
                        .WithMany("LieuxRestauration")
                        .HasForeignKey("NumPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.PhotoClub", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", "Club")
                        .WithMany()
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("NumPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.PrixPeriode", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.TypeChambre", "TypeChambre")
                        .WithMany("PrixPeriodes")
                        .HasForeignKey("IdTypeChambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Periode", "Periode")
                        .WithMany("PrixPeriodes")
                        .HasForeignKey("NumPeriode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periode");

                    b.Navigation("TypeChambre");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Reservation", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", "Club")
                        .WithMany("Reservations")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Transport", "Transport")
                        .WithMany("Reservations")
                        .HasForeignKey("IdTransport")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("NumClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Club");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.ReservationActivite", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Activite", "Activite")
                        .WithMany("ReservationActivites")
                        .HasForeignKey("IdActivite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Reservation", "Reservation")
                        .WithMany("ReservationActivites")
                        .HasForeignKey("NumReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activite");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.SousLocalisation", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Photo", "Photo")
                        .WithMany("SousLocalisations")
                        .HasForeignKey("NumPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Station", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Photo", "Photo")
                        .WithMany("Stations")
                        .HasForeignKey("NumPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Transaction", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.CarteBancaire", "CarteBancaire")
                        .WithMany("Transactions")
                        .HasForeignKey("IdCb");

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Reservation", "Reservation")
                        .WithMany("Transactions")
                        .HasForeignKey("NumReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarteBancaire");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.TypeActivite", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Photo", "Photo")
                        .WithMany("TypeActivites")
                        .HasForeignKey("NumPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.TypeChambre", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", "Club")
                        .WithMany("TypeChambres")
                        .HasForeignKey("IdClub");

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Photo", "Photo")
                        .WithMany("TypeChambres")
                        .HasForeignKey("NumPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("assure_la_liaison_avec", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.TypeChambre", null)
                        .WithMany()
                        .HasForeignKey("idtypechambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.EquipementSalleDeBain", null)
                        .WithMany()
                        .HasForeignKey("numequipementsallebain")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("collabore", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", null)
                        .WithMany()
                        .HasForeignKey("idclub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Categorie", null)
                        .WithMany()
                        .HasForeignKey("numcategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("converge_vers", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", null)
                        .WithMany()
                        .HasForeignKey("idclub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Regroupement", null)
                        .WithMany()
                        .HasForeignKey("numregroupement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fusionne", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", null)
                        .WithMany()
                        .HasForeignKey("idclub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.LieuRestauration", null)
                        .WithMany()
                        .HasForeignKey("numrestauration")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fusionne_avec", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Categorie", null)
                        .WithMany()
                        .HasForeignKey("numcategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Localisation", null)
                        .WithMany()
                        .HasForeignKey("numlocalisation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("incruste_avec", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Activite", null)
                        .WithMany()
                        .HasForeignKey("idactivite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", null)
                        .WithMany()
                        .HasForeignKey("idclub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("photoavis", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Avis", null)
                        .WithMany()
                        .HasForeignKey("numavis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Photo", null)
                        .WithMany()
                        .HasForeignKey("numphoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("s_articule_autour_de", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Localisation", null)
                        .WithMany()
                        .HasForeignKey("numlocalisation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.SousLocalisation", null)
                        .WithMany()
                        .HasForeignKey("numpays")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("s_harmonise_avec", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Categorie", null)
                        .WithMany()
                        .HasForeignKey("numcategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.TypeClub", null)
                        .WithMany()
                        .HasForeignKey("numtype")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("s_imbrique_dans", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.TypeChambre", null)
                        .WithMany()
                        .HasForeignKey("idtypechambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Service", null)
                        .WithMany()
                        .HasForeignKey("numservice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("s_influence_mutuellement", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.TypeChambre", null)
                        .WithMany()
                        .HasForeignKey("idtypechambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Chambre", null)
                        .WithMany()
                        .HasForeignKey("numchambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("s_unit_a", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.Club", null)
                        .WithMany()
                        .HasForeignKey("idclub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Chambre", null)
                        .WithMany()
                        .HasForeignKey("numchambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("se_met_en_harmonie_avec", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.TypeChambre", null)
                        .WithMany()
                        .HasForeignKey("idtypechambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.Equipement", null)
                        .WithMany()
                        .HasForeignKey("numequipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("synchronise", b =>
                {
                    b.HasOne("ClubMedAPI.Models.EntityFramework.TypeChambre", null)
                        .WithMany()
                        .HasForeignKey("idtypechambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMedAPI.Models.EntityFramework.PointFort", null)
                        .WithMany()
                        .HasForeignKey("numpointfort")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Activite", b =>
                {
                    b.Navigation("Adulte");

                    b.Navigation("Enfant");

                    b.Navigation("ReservationActivites");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Adresse", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.CarteBancaire", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Chambre", b =>
                {
                    b.Navigation("Disponibilites");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Client", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("CartesBancaires");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Club", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("Disponibilites");

                    b.Navigation("Reservations");

                    b.Navigation("TypeChambres");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.EquipementSalleDeBain", b =>
                {
                    b.Navigation("Icons");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Icon", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Partenaire", b =>
                {
                    b.Navigation("Activites");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Periode", b =>
                {
                    b.Navigation("PrixPeriodes");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Photo", b =>
                {
                    b.Navigation("ClubsAvecCettePhoto");

                    b.Navigation("LieuxRestauration");

                    b.Navigation("SousLocalisations");

                    b.Navigation("Stations");

                    b.Navigation("TypeActivites");

                    b.Navigation("TypeChambres");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.PointFort", b =>
                {
                    b.Navigation("Icons");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Reservation", b =>
                {
                    b.Navigation("AutresVoyageurs");

                    b.Navigation("Avis");

                    b.Navigation("ReservationActivites");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Service", b =>
                {
                    b.Navigation("Icons");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.SousLocalisation", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.TrancheAge", b =>
                {
                    b.Navigation("ActivitesEnfants");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.Transport", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.TypeActivite", b =>
                {
                    b.Navigation("ActivitesAdultes");
                });

            modelBuilder.Entity("ClubMedAPI.Models.EntityFramework.TypeChambre", b =>
                {
                    b.Navigation("Chambres");

                    b.Navigation("PrixPeriodes");
                });
#pragma warning restore 612, 618
        }
    }
}
